# This file contains all the important settings for your n8n setup

# Settings for the user that will manage Docker
docker_user: docker # Username for managing Docker
docker_user_password: "your-password" # Password for this user
ssh_public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}" # Your SSH key for secure access

# Settings for your n8n installation
n8n_port: 5678 # The port n8n will use
domain_name: "yourdomain.com" # Your main domain name
subdomain: "n8n" # The subdomain for n8n
n8n_host: "{{ subdomain }}.{{ domain_name }}" # Full website address for n8n
timezone: "Europe/Berlin" # Your local timezone
